### ISSUE TITLE
Workflow with type: approval - JOB NUM is null

### ISSUE THREAD

**Issue by viniciusclemente** [CircleCI-Public/sumologic-orb#16]
### Orb version

1.0.2

### What happened

When there is a job with type: approval, sumologic-orb fails. **JOB NUM: null**
![image](https://user-images.githubusercontent.com/40431981/69635812-f8b1cd80-1033-11ea-8262-42ed02c863f5.png)
![image](https://user-images.githubusercontent.com/40431981/69636010-707ff800-1034-11ea-8727-2580780ca1b9.png)

### Expected behavior

Runs successfully and sends to Sumo Logic.

**Comment by mvxt** [comment]
Hey @viniciusclemente just merged and confirmed fix is working. See example job here w/ output: https://circleci.com/gh/mvxt/circleci-demo/916

Give it a try and let us know if you're still seeing issues.
