### ISSUE TITLE
Feature Request: Ability to rerun workflows and have data output of workflow appear in Sumo Logic

### ISSUE THREAD

**Issue by ianhundere** [CircleCI-Public/sumologic-orb#22]
### Orb version
1.0.6

### What happened

It appears as if data only flows into Sumo Logic at the onset of a workflow running, but not for workflows that have failed and then are rerun from the beginning.

Let's say a workflow fails and you're alerted of this failure. If you try to rerun the workflow (including the job `sumologic/workflow-collector`) in CircleCI, no data is ingested in Sumo Logic. 

So only the initial running of a workflow is ingested into Sumo Logic and not any reruns thereafter.

### Expected behavior

Ideally, you should be able to rerun the entire workflow (including the `sumologic/workflow-collector` job) and all log output should be ingested into Sumo Logic, but again, this is not the case currently.

**Comment by KyleTryon** [comment]
Hello @ianhundere, 

I would have expected this should work. When you re-ran the workflow did you receive any errors from the workflow-collector job? Any meaningful output you could share?

**Comment by ianhundere** [comment]
Hey @KyleTryon,

When I re-ran the workflow I received no output whatsoever and this is across any workflow that's using the Sumo Logic collector orb. After it runs the first time, all logs are no longer ingested if you re-run it; just silence. 

Below is a screenshot of the ingestion of logs from the CircleCI collector we have configured. I had just re-run a workflow and nothing was ingested into Sumo.

![image](https://user-images.githubusercontent.com/138915/80718895-bb60d880-8ac8-11ea-83c0-3eefe815e1c3.png)

Not a huge deal at the moment, but if a workflow fails and we re-run it, it would be nice to be alerted on any problematic logs. Let me know if I can provide any further insight.

**Comment by KyleTryon** [comment]
Hello, 

Thank you for your contributions. We have connected with SumoLogic to take over ownership of this orb. We will be archiving this repository shortly.

The new SumoLogic orb and repository can be found here:
 - repo: https://github.com/SumoLogic/sumologic-orb
 - orb: https://circleci.com/developer/orbs/orb/sumologic/sumologic

Ensure to update the orb reference in your config with the orb now under the SumoLogic namespace.

```
orbs:
  sumologic: sumologic/sumologic@2.1.0
```
