### ISSUE TITLE
Orb Version 1.0.6/Pending Jobs

### ISSUE THREAD

**Issue by pat0010110** [CircleCI-Public/sumologic-orb#23]
### What happened

When adding the `sumologic/workflow-collector` job to either the beginning or end of a workflow, the job will skip over jobs in `STATUS: "on_hold"` and `STATUS: "blocked"`,  resulting in the orb's `workflow-collector` job ending its collection and shipping incomplete logs to sumologic. The logs of the inflight (on_hold, blocked, etc.) jobs are never collected, as the orb's job does not wait for them to complete, nor circle back to check on them.

Below is (partial) sample output of the orb skipping two jobs then shipping workflow logs to sumologic. Neither the logs for `JOB: "approve-tf"` nor those for `JOB: "publish-docker-image-1"`, below, are included in the logs sent to sumologic, though the orb does appear to consider this a successful run of its workflow-collector job.

<img width="1151" alt="ApparentlySuccessfulWorkflow-CollectorJob" src="https://user-images.githubusercontent.com/54034821/80652096-155f9080-8a2c-11ea-8292-5e90f50b8fc3.png">

### Expected behavior

The orb would have logic to gracefully handle blocked, on_hold, or otherwise pending jobs and to include, not ignore, those jobs' completed build logs to sumologic.

**Comment by KyleTryon** [comment]
Hello @pat0010110,

This change was introduced on purpose somewhat recently. The workflow-collector job can only run for a maximum of 5 hours, which would cost you a lot of credits, and if you did not accept the on_hold job within that time, we would automatically kill the running workflow-collector job and cause an error in your build.

This is an unfortunate limitation of the orb, this was the best solution we could determine for the time being.

**Comment by pat0010110** [comment]
Does the behavior apply as well to blocked jobs? Would it be possible to gracefully handle blocked, not on_hold, jobs and return their workflows?
