### ISSUE TITLE
Orb triggers end of workflow process when workflow is still running

### ISSUE THREAD

**Issue by sumo-drew** [CircleCI-Public/sumologic-orb#25]
### Orb version

1.0.6

### What happened

The orb thinks that the workflow is either blocked or on hold (due to, for example, a manual quality gate) and then sends the end of workflow data to Sumo Logic. However, the workflow is fully automated 

### Expected behavior

The workflow is fully automated, so we do not expect a blocked or on_hold status to be returned from the workflow get-jobs API. It appears there may be a case where one of these two statuses are returned even for fully automated worfklows. Here is the code that assumes these statuses are not returned for automated workflows:

```bash
              if [ "$JOB_STATUS" == '"success"' ] || [ "$JOB_STATUS" == '"failed"' ];
              then
                echo "Job $JOB_NAME $JOB_NUMBER is complete - $JOB_STATUS"
              elif [ "$JOB_STATUS" == '"on_hold"' ] || [ "$JOB_STATUS" == '"blocked"' ];
              then
                # The condition to not block metrics sending when workflow use manually approved steps or is blocked.
                echo "Job $JOB_NAME $JOB_NUMBER need manual approval - $JOB_STATUS - skipping"
              else
                # If it is still running, then mark WF_FINISHED as false.
                WF_FINISHED=false
                echo "Setting status of WF_FINISHED to false"
              fi
            fi
```

The current thinking is the API may be returning "on_hold" or "blocked" in certain cases for automated workflows (potentially even as designed). If that's the case, we would need to understand those cases so that we do not assume the workflow is finished prematurely.

**Comment by KyleTryon** [comment]
Hello, 

Thank you for your contributions. We have connected with SumoLogic to take over ownership of this orb. We will be archiving this repository shortly.

The new SumoLogic orb and repository can be found here:
 - repo: https://github.com/SumoLogic/sumologic-orb
 - orb: https://circleci.com/developer/orbs/orb/sumologic/sumologic

Ensure to update the orb reference in your config with the orb now under the SumoLogic namespace.

```
orbs:
  sumologic: sumologic/sumologic@2.1.0
```
