### ISSUE TITLE
Feature Request: Add parameterizable image for default executor

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/sumologic-orb#4]
The current default executor used in the workflow-collector job has a hard-coded docker image "cimg/base". As per best practice, the image or tag version should be parameterized to protect the executor against potential volatile changes to the docker image.

**Comment by judahtanthony** [comment]
Can you publish this fix to the Orb registry?  The current one https://circleci.com/orbs/registry/orb/circleci/sumologic#executors-default seems to lack this functionality.

**Comment by nialloc9** [comment]
<img width="1325" alt="Screenshot 2019-10-22 at 16 11 56" src="https://user-images.githubusercontent.com/14121652/67304621-041d5080-f4ec-11e9-82f4-4df952a0feb3.png">

Can this please be published as it causing a production issue on circle ci integration using this orb?

**Comment by judahtanthony** [comment]
FYI, I'm currently working on [inlining this orb](https://circleci.com/docs/2.0/orb-author/#writing-inline-orbs) using the [github source](https://github.com/CircleCI-Public/sumologic-orb).  I'm currently running into a couple of bugs for example the line `if [ "$JOB_STATUS" != '"running"' ];` is insufficient to indicate that the job is complete, as there are many non-"running" states (like blocked and queued).  I'm testing a fix, but i'm also getting an odd mis-match in the outputs of the circleci API (sometimes it is missing the `job_number`).  I'll post any progress.

**Comment by judahtanthony** [comment]
So I have fix the afore mentioned bug in: https://github.com/CircleCI-Public/sumologic-orb/pull/11
