### ISSUE TITLE
Feature Request: Process workflow status

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/sumologic-orb#5]
Currently, only job information is captured and displayed within the sumo logic dashboard. Workflow data at the end of the job must be processed before it can be displayed on sumo logic. Because the sumo-logic job runs within the workflow it is tracking, it must first determine if the workflow has failed based on the results of the other jobs and then modify the data before sending. this is already done for job data.

https://github.com/CircleCI-Public/sumologic-orb/blob/master/src/jobs/workflow-collector.yml#L142

Determine the correct status for the workflow before sending. Once a PR has been merged for this change, a change will need to be made to the official Sumo Logic dashboard.

**Comment by ulziibay** [comment]
I am claiming this one!
