### ISSUE TITLE
Find no jobs in workflow, exits with status 1, other jobs running

### ISSUE THREAD

**Issue by gworley3** [CircleCI-Public/sumologic-orb#6]
### Orb version

1.0.0

### What happened

Followed setup instructions, getting an error message running the workflow collector:

```
Jobs in Workflow: 0

Only a single job has been found in the workflow, indicating this reporter is the only job in the pipeline.
Please add other jobs to the Workflow you wish to collect data on to send to Sumologic
Exited with code 1
```

I talked with support and they suggested I file a ticket here. They reviewed my config and confirmed it matches the instructions. Link to it failing:

https://circleci.com/gh/AdStage/adstage-platform-v2/1123?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### Expected behavior

Runs successfully and sends to Sumo Logic.

**Comment by gupta-ayush3210** [comment]
@gworley3 Happened with me, I was missing setting up `circle-token` in circle environment. It was hard to find but here is this:
https://circleci.com/orbs/registry/orb/circleci/sumologic
See the jobs section.

**Comment by jps** [comment]
We are also experiencing this issue, Tried adding the the circle token as suggested above but no luck.


As you can see there are other build steps which are running

![image](https://user-images.githubusercontent.com/350953/68749109-9a2d2e00-05f5-11ea-9616-6c61e6bf2293.png)

Our workflow is something like
```
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - sumologic/workflow-collector
      - install_deps:
          <<: *ignore_release
```

thought maybe it's unable to understand the key merge, removed that, still not working...

**Comment by KyleTryon** [comment]
Hello all, can anyone confirm if this is still an issue? Ther have been some large updates since this issue was last commented on. We are aware of some limitations of this orb but this issue should be resolved. Please ensure you are on version `1.0.6` https://circleci.com/orbs/registry/orb/circleci/sumologic

We will close this issue in two weeks if there is no response.

**Comment by seanriordan08** [comment]
For anyone else finding themselves here - one suggestion to solve "No Workflow Found":
1. create a personal token called `circle-token`, and copy the value
2. create an env var on your project named `CIRCLE_TOKEN` and set the value to your `circle-token`

**Comment by gmemstr** [comment]
@seanriordan08 To confirm, have you encountered this same issue recently?

**Comment by seanriordan08** [comment]
@gmemstr, back in early October I found myself here while scouring for clues on how to address an error that reported "No Workflow Found", which is not the exact issue described in the ticket. The orb works for me currently, but as a suggestion, if an error reports "No Jobs in Workflow", carefully examine your `config.yml` to ensure your workflow is specified, and no branch filters are in place to ignore your expected workflow. Lastly, if my post was interpreted as noise, it was not my intent 😄

**Comment by KyleTryon** [comment]
Hello, 

Thank you for your contributions. We have connected with SumoLogic to take over ownership of this orb. We will be archiving this repository shortly.

The new SumoLogic orb and repository can be found here:
 - repo: https://github.com/SumoLogic/sumologic-orb
 - orb: https://circleci.com/developer/orbs/orb/sumologic/sumologic

Ensure to update the orb reference in your config with the orb now under the SumoLogic namespace.

```
orbs:
  sumologic: sumologic/sumologic@2.1.0
```
